apiVersion: webapp.liasawesomeapp.kubebuilder.io/v1
kind: SillyWebapp
metadata:
  labels:
    app.kubernetes.io/name: sillywebapp
    app.kubernetes.io/instance: sillywebapp-sample
    app.kubernetes.io/part-of: lias-awesome-app
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lias-awesome-app
  name: sillywebapp-sample
spec:
  # TODO(user): Add fields here
